Content_ag/Content_Scriber/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
]

Content_ag/Content_ag/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^Scriber/', include('Content_Scriber.urls')),
	url(r'^admin/', admin.site.urls),
]

content_aggregator_v/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^registration/', include('registration.urls')),
	url(r'^admin/', admin.site.urls),
	url(r'^summernote/',include('django_summernote.urls'))
]

registration/urls.py
from django.conf.urls import url
from . import views

app_name = 'registration'

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^jobseeker/$', views.get_user, name='registerUser'),
    url(r'^jobseeker/thanks/$', views.thanks, name='thanks'),
    url(r'^jobprovider/$', views.get_comapny, name='registerCompany'),
    url(r'^jobprovider/thanks/$', views.thanks, name='thanks'),
    url(r'^jobsubmit/$', views.get_job, name='Job Submit'),
    url(r'^jobapplication/(?P<details>.+)/$', views.get_application, name='application'),
    url(r'^userprofile/edit/$', views.edit_profile_user, name='Profile Edit User'),
    url(r'^companyprofile/edit/$', views.edit_profile_company, name='Profile Edit company'),
    url(r'^confirmjob/(?P<text>.+)/$', views.accepting_letter, name='confirmjob'),
    url(r'^loginuser/$', views.checkuserlogin, name='login User'),
    url(r'^search/$', views.search_job, name='Search Job'),
    url(r'^logincompany/$', views.checkcompanylogin, name='login company'),
    url(r'^login/user/$', views.login_user, name='user allowed'),
    url(r'^login/company/$', views.login_Company, name='user allowed'),
    url(r'^userprofile/$', views.userprofile, name='profileuser'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^companyprofile/$', views.companyprofile, name='profilecompany'),
    url(r'^updateprofileuser/$',views.update_profile_user,name='updateuser'),
    url(r'^updateprofilecompany/$',views.update_profile_company,name='updatecompany'),
    url(r'^jobview/$',views.displayjob,name = 'display'),
    url(r'^applicationview/$', views.displayapplication, name='viewapplication'),
    url(r'^submittedapplications/$', views.submitted_application, name='submittedapplication'),
    url(r'^deletejob/(?P<text>.+)/$', views.Delete_job, name='Delete Job'),
    url(r'^profilecheck/$', views.profile_check, name='profilecheck'),

]

Content_ag/Content_Scriber/models.py
from django.db import models

""" Defining the Job publishing form field """



class job_details(models.Model):
        
	details = models.CharField(max_length=100000)
        pay = models.CharField(max_length=50)
        deadline = models.DateTimeField('Date to complete the project till')
	pub_date = models.DateTimeField('date published')

""" defining the job Application submit field """

class job_application(models.Model):
	question = models.ForeignKey(job_details, on_delete=models.CASCADE)
	Application_text = models.CharField(max_length=100000)
	status = models.BooleanField(default=10)

Content_ag/Content_Scriber/views.py
from django.http import HttpResponse

def index(request):
	return HttpResponse("Hello, world. You're at the polls index.")

templates/JobApplication/JobApplication.html
<form  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

templates/JobSubmit/JobSubmit.html
<form  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

templates/all_jobs.html
{% load static %}

<html>
	<head>
			<link rel="stylesheet" type="text/css" href="{%  static '../static/css/profile.css' %} ">





			<header>
			<div>
			 <ul>
				  <li><a class="active" href="{% url 'registration:home' %}">Home</a></li>
				   <li><a href="{% url 'registration:Search Job' %}">Search</a></li>
				  
				  
                    {% if flag == "on" %}
                        <li id="login"><a href="">login</a>
                      <ul class="dropdown">
                      <li ><a href="{% url 'registration:login company' %}">Company</a></li>
                      <li ><a href="{% url 'registration:login User' %}"> User</a></li>

                      </ul>
                      <li id="signup"><a href="">Signup</a>
                      <ul class="dropdown">
                      <li><a href="{% url 'registration:registerCompany' %}">Company</a></li>
                      <li><a href="{% url 'registration:registerUser' %}">Job seeker</a></li>
                    {% endif %}
                    {% if flag == "off" %}
                      <li><a href="{% url 'registration:Job Submit' %}">Post a job</a></li>
                    {% endif %}
                    
                  </ul>
				</ul>
			</div>
			</header>
	</head>
	<body background="{% static '../static/image/blue.png' %}">

      <h3> Search Successfull Click the respective job detail to submit application  </h3>
     {%  for JobDetails in search %}

         <a href="{% url 'registration:application' JobDetails.details %}"> <p> Job Details :{{ JobDetails.details }}</p></a>
         <p> Job Pay : {{ JobDetails.pay }}</p>
         <p> Job Deadline : {{ JobDetails.deadline }}</p>

     {% endfor %}

		<footer>
			<div class="Manageby">
			<h4> MANAGE AND PUBLISHEDBY:</h4>
				<div>VAIBHAB BAJPAI ||  KUNAL RAJPUT  || KANIKA SINGHAL</div>
			</div>
			<div class="companylogo">
						<img id="img1" src="{% static '../static/image/book1.png' %}" alt="company logo" >
			</div>
			<div class="followus">
				<h4>FOLLOW US:</h4>
				<a href="https://www.facebook.com">
				<img id="link" alt="followus" src="{% static '../static/image/facebook.png' %}" >
				<a href="http://www.twitter.com">
				<img id="link" alt="followus" src="{% static '../static/image/twitter.png' %}" >
				<a href="https://www.youtube.com">
				<img id="link" alt="followus" src="{% static '../static/image/youtube.png' %}" >
			</div>
		</footer>
 </body>
</html>

templates/home.html
{% load static %}
<html>

	<head>
			<link rel="stylesheet" type="text/css" href="{% static './css/home.css'%}">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">			
	</head>
	<body onLoad="noBack();" onpageshow="if (event.persisted) noBack();" onUnload="">
	<header>
			<div>
                <ul class="nav">

				   <li><a class="nav_left" href="{% url 'registration:home' %}">Home</a></li>
				   <li><a href="{% url 'registration:Search Job' %}">Search</a></li>
				  
				  
                    {% if flag == "on" %}
                        <li class="nav_right"><a href="">login</a>
                      <ul class="dropdown" style="list-style:none;">
                      <li ><a href="{% url 'registration:login company' %}">Company</a></li>
                      <li ><a href="{% url 'registration:login User' %}"> Job Seeker</a></li>

                      </ul>
                      <li class="nav_right"><a href="">Signup</a>
                      <ul class="dropdown" style="list-style:none;">
                      <li><a href="{% url 'registration:registerCompany' %}">Company</a></li>
                      <li><a href="{% url 'registration:registerUser' %}">Job seeker</a></li>
                    {% endif %}
                    {% if flag == "off" %}
                      <li><a class="nav_left" href="{% url 'registration:Job Submit' %}">Post a job</a></li>
                        <li><a class="nav_left" href="{% url 'registration:profilecheck' %}">Profile</a></li>
                        <li><a class="nav_right" href="{% url 'registration:logout' %}">Logout</a></li>
                    {% endif %}
                  </ul>

				  
				 
				</ul>
			</div>
			</header>

            {% if messages %}
                         <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                         </ul>
            {% endif %}

			<div class="herotext">
				<div class="textheading">
				<p> -Scriber Membership-</p>
				</div>

				
				<div class="text">
				<p> Writing is the painting of voice.....</p>
				</div>
				
				<div class="text2">
				<p> Join Us</p>
				</div>
				
				
			
			</div>
	
			<div class="animationimages" >
			<img class="mySlides" src="{% static './image/hero1.png' %}" >
			<img class="mySlides" src="{% static './image/hero2.png' %}" >
			<img class="mySlides" src="{% static './image/hero3.png' %}" >	
			
			</div>
			

			
			
		
			<div class="aboutscriber">
				<div class="scriberheading">
				<h2> About Scriber</h2>
				</div>
				<div class="scribertext">
				<p>
				<div>Aggregator refers to a web site or computer software that aggregates a specific type of information
				from multiple online sources:</div>
				<div>This project mainly focus on the writers group of our society those who are efficient enough to write professionally. </div>
				<div>This website will provide them a platform to work in their respective writing domain from home or remote locations. </div>
				<div>This website also benefit the organizations who require literature content or written material but not as frequent due to
				which they have to hire someone.</div>
				<div>So they can post their job in acquaintance with their specifications so that people can apply 
				and post their job applications comfortably.</div></p>
				</div>
			</div>
			
		<div class="company">	
		 <div class="animationcompany" >
			<img class="slidecompany" src="{% static './image/advertisement3.png'  %}" >
			<img class="slidecompany" src="{% static './image/advertisement3text.png'%}" >
		</div>	
		</div>
		
		<div class="genre">
			<div class="genreimg1">
			<img class="inkpot1" src="{% static './image/inkpot2.png' %}" >
			</div>
			
			
			
			
			
			<div class="genreheading">
			<h2>Genre</h2>
			
			
			<div class="genretext">
			<p>
					<div id="genretext1"> Blog</div>
					<div id="genretext1"> Novel</div>
					<div id="genretext1"> Magzine</div>
					<div id="genretext1"> Editorial</div>
					<div id="genretext1"> Short Story</div>
					<div id="genretext1"> Fiction</div>
					
					
			</p>
			</div>
			</div>
			<div class="genreimg2">
			<img class="inkpot1" src="{% static './image/inkpot.png' %}" >
			</div>
			
			
		</div>
		
		
		
		<div class="jobseeker">	
		 <div class="animationjobseeker" >
			<img class="slidejobseeker" src="{% static './image/jobseekerphoto.png' %}" >
			<img class="slidejobseeker" src="{% static './image/jobseekertext.png' %}" >
		</div>	
		</div>
		
		
		<div class="companyrights">
				<div class="companyrights_text">
				<div class="companyinfotext1" id="companyinfo">
				<h4>Company Info</h4> 
				
				<p>
					<div>Projects</div>
					<div>Contests</div>
					<div>Sitemap</div>
					<div>Freelancer Local</div>
					<div>Services</div>
					<div>Escrow</div>
					<div>Warrior Forum</div>
					<div>Freemarket</div>
				</p>
				</div>


				</div>
				<div class="companyrights_text">
				<div class="companyinfotext1">
					<h4>Additional Services</h4>
					
					<div>Projects</div>
					<div>Contests</div>
					<div>Sitemap</div>
					<div>Freelancer Local</div>
					<div>Services</div>
					<div>Escrow</div>
					<div>Warrior Forum</div>
					<div>Freemarket</div>
					
					</p>
					</div>
				</div>
				<div class="companyrights_text">
			<div class="companyinfotext1">
					
					<h4>Browser</h4>
					
					<p>
					<div>Projects</div>
					<div>Contests</div>
					<div>Freelancer Local</div>
					<div>Services</div>
					<div>Escrow</div>
					<div>Warrior Forum</div>
					<div>Freemarket</div>
					<div>Escrow</div>
					
					
					</p>
					</div>
				</div>
		</div>
		
		<footer>
			<div class="Manageby">
			<h4> MANAGE AND PUBLISHEDBY:</h4>
				<div>VAIBHAB BAJPAI ||  KUNAL RAJPUT  || KANIKA SINGHAL</div>
			</div>
			<div class="companylogo">
						<img id="img1" src="{% static './image/book1.png' %}" alt="company logo" >
			</div>
			<div class="followus">
				<h4>FOLLOW US:</h4>
				<a href="https://www.facebook.com">
				<img id="link" alt="followus" src="{% static './image/facebook.png' %}" >
				<a href="http://www.twitter.com">
				<img id="link" alt="followus" src="{% static './image/twitter.png'%}">
				<a href="https://www.youtube.com">
				<img id="link" alt="followus" src="{% static './image/youtube.png' %}" >
			</div>
		</footer>

		
		<script>
			var myIndex1=0;
			element1();
			function element1()
			{
				var i;
				var x=document.getElementsByClassName("mySlides");
				for(i=0;i<x.length;i++)
				{
				x[i].style.display="none";
				}
				myIndex1++;
				if(myIndex1 > x.length)
				{
				myIndex1=1;
				}
				x[myIndex1-1].style.display = "block";
				setTimeout(element1, 2000);
			}
			
			
			
			var myIndex2=0;
			element2();
			function element2()
			{
				var i;
				var x=document.getElementsByClassName("slidecompany");
				for(i=0;i<x.length;i++)
				{
				x[i].style.display="none";
				}
				myIndex2++;
				if(myIndex2 > x.length)
				{
				myIndex2=1;
				}
				x[myIndex2-1].style.display = "block";
				setTimeout(element2, 4000);
			}
			
			
			
			var myIndex3=0;
			element3();
			function element3()
			{
				var i;
				var x=document.getElementsByClassName("slidejobseeker");
				for(i=0;i<x.length;i++)
				{
				x[i].style.display="none";
				}
				myIndex3++;
				if(myIndex3 > x.length)
				{
				myIndex3=1;
				}
				x[myIndex3-1].style.display = "block";
				setTimeout(element3, 4000);
			}

                window.history.forward();
                function noBack()
                {
                    window.history.forward();
                }


		</script>	
    </body>
		
</html>

templates/logout.html
{% load static %}

<html>
	<head>
			<link rel="stylesheet" type="text/css" href="{%  static '../static/css/profile.css' %} ">





			<header>
			<div>
				<ul>
				<li><a class="active" href="{% url 'registration:home' %}">Home</a></li>
				  <li><a href="{% url 'registration:Job Submit' %}">Post a job</a></li>
				  <li><a href="{% url 'registration:Search Job' %}">Search</a></li>
				  <li id="login"><a href="{% url 'registration:login User' %}">login User</a></li>
				  <li id="login"><a href="{% url 'registration:login company' %}">login company</a></li>
				  <li id="signup"><a href="#about">Signup</a>
				  <ul class="dropdown">
				  <li><a href="{% url 'registration:registerCompany' %}">Company</a></li>
				  <li><a href="{% url 'registration:registerUser' %}">Job seeker</a></li>
				  </ul>
				  </li>


				</ul>
			</div>
			</header>
	</head>
	<body background="{% static '../static/image/blue.png' %}">
        <h3>You are succesfully Logged Out</h3>

		<footer>
			<div class="Manageby">
			<h4> MANAGE AND PUBLISHEDBY:</h4>
				<div>VAIBHAB BAJPAI ||  KUNAL RAJPUT  || KANIKA SINGHAL</div>
			</div>
			<div class="companylogo">
						<img id="img1" src="{% static '../static/image/book1.png' %}" alt="company logo" >
			</div>
			<div class="followus">
				<h4>FOLLOW US:</h4>
				<a href="https://www.facebook.com">
				<img id="link" alt="followus" src="{% static '../static/image/facebook.png' %}" >
				<a href="http://www.twitter.com">
				<img id="link" alt="followus" src="{% static '../static/image/twitter.png' %}">
				<a href="https://www.youtube.com">
				<img id="link" alt="followus" src="{% static '../static/image/youtube.png' %}" >
            </div>
		</footer>
 </body>
</html>

templates/post_job.html
{% load static %}
<html>
	<head>
			<link rel="stylesheet" type="text/css" href="{% static './css/post_job.css' %}">
		
			


	
			<header>
			<div>
				<ul class="nav">
				  <li><a class="nav_left" href="{% url 'registration:home' %}">Home</a></li>
				   <li><a class="nav_left"href="{% url 'registration:Search Job' %}">Search</a></li>
				  
				  
                    {% if flag == "on" %}
                        <li class="nav_right"><a href="">login</a>
                      <ul class="dropdown">
                      <li ><a href="{% url 'registration:login company' %}">Company</a></li>
                      <li ><a href="{% url 'registration:login User' %}"> Job seeker</a></li>

                      </ul>
                      <li class="nav_right"><a href="">Signup</a>
                      <ul class="dropdown">
                      <li><a href="{% url 'registration:registerCompany' %}">Company</a></li>
                      <li><a href="{% url 'registration:registerUser' %}">Job seeker</a></li>
                    {% endif %}
                    {% if flag == "off" %}
                        <li><a class="nav_left"href="{% url 'registration:Job Submit' %}">Post a job</a></li>
                        <li><a class="nav_left" href="{% url 'registration:profilecheck' %}">Profile</a></li>
                        <li><a class="nav_left" href="{% url 'registration:logout' %}">logout</a></li>

                    {% endif %}

                    
                  </ul>


				  </ul>
				  </li>
				  
				 
				</ul>
			</div>
			</header>
	</head>

	<body background="{% static './image/blue.png' %}">
            {% if post == "on" %}
		
	        <li ><a href="{% url 'registration:profilecompany' %}"> Profile</a></li>
            <div class="companyform">
				<form method="post">
				 <h3>Post a job</h3>
					{% if messages %}
                         <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                         </ul>
                    {% endif %}
			        {% csrf_token %}
				    {{ form.as_p }}
			    <fieldset class="account-action">
				    <input class="btn" type="submit" name="submit" value="Submit">
			   
			    </fieldset>
			    </form>
				
			</div>
	    <div class="img">
           <img src="{% static './image/pic1.png' %}" height="50%" width="40%" >

	    </div>
	    <div class="content">
          <p class="post">It's always nice to hire the best talent available for the best efficiency and scribber offers you tha way to achieve the Same.<br>Post a job and hire the best one suited for the job,Posting the Job on Our site means that all our users can see the Job as well as they can apply for any job by searching according to the Genre and Pay fields.</p>

	    </div>
            {% else %}
              <h3>Please Login as a Company First :<a href="{% url 'registration:login company' %}">Login Company</a></h3>
		    {% endif %}
		 

		 
		 
		<footer>
			<div class="Manageby">
			<h4> MANAGE AND PUBLISHED BY:</h4>
				<div>VAIBHAV BAJPAI ||  KUNAL RAJPUT  || KANIKA SINGHAL</div>
			</div>
			<div class="followus">
				<h4>FOLLOW US:</h4>
				<a href="https://www.facebook.com">
				<img id="link" alt="followus" src="{% static './image/facebook.png' %}" >
				<a href="http://www.twitter.com">
				<img id="link" alt="followus" src="{% static './image/twitter.png' %}">
				<a href="https://www.youtube.com">
				<img id="link" alt="followus" src="{% static './image/youtube.png' %}" >
			</div>
		</footer>
 </body>
</html>

templates/profile_user.html
{% load static %}

<html>
	<head>
			<link rel="stylesheet" type="text/css" href="{%  static '../static/css/profile_user.css' %} ">
            <header>
			
				<ul class="nav">
                      <li><a class="nav_left" href="{% url 'registration:home' %}">Home</a></li>
				   <li><a class="nav_left"href="{% url 'registration:Search Job' %}">Search</a></li>
				  
				  
                    {% if flag == "on" %}
                        <li class="nav_right"><a href="">login</a>
                      <ul class="dropdown">
                      <li ><a href="{% url 'registration:login company' %}">Company</a></li>
                      <li ><a href="{% url 'registration:login User' %}"> Job seeker</a></li>

                      </ul>
                      <li class="nav_right"><a href="">Signup</a>
                      <ul class="dropdown">
                      <li><a href="{% url 'registration:registerCompany' %}">Company</a></li>
                      <li><a href="{% url 'registration:registerUser' %}">Job seeker</a></li>
                    {% endif %}
                    {% if flag == "off" %}

                        <li><a class="nav_right" href="{% url 'registration:logout' %}">logout</a> </li>
                    {% endif %}
                  </ul>

				  
				 
				</ul>
			
			</header>
	</head>
	<body>
   
		<div class="profile" >
			<ul>
            <li><a href="{% url 'registration:viewapplication' %}">Applications</a></li>
            <li><a href="{% url 'registration:updateuser' %}">Edit Profile</a></li>
			</ul>
            {% if messages %}
                         <ul class="messages">
                            {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                            {% endfor %}
                         </ul>
            {% endif %}
			
		</div>
		<div>
			<div class="left_text" style="float:left;">
				<div class="text">
				<div><h2>Genre</h2></div>

				<div>	Blog</div>
				<div>	Novel</div>
				<div>	Magzine</div>
				<div>	Editorial</div>
			
				<div>	Short Story</div>
				<div>	Fiction</div>
				</div>
		</div>		
	
			<div class="info" >			
			<img src = "../{{ user.img }} " height="10px" width="10px">
			<h2>User Name : {{ user.user_name }}</h2>
            <div class="personal">
            	<h3>Personal Details</h3>
                <p>First Name : {{ user.first_name }}<p>
                <p>Last Name : {{ user.last_name }}<p>
            </div>
            <div class="contact">
            	<h3>Contact Details</h3>
                <p>Email Id: {{ user.email_id }}<p>
                <p>Address : {{ user.address }}<p>
                <p>Contact Number : {{ user.contact_number }}<p>
                <img src = "D:/python project/Content_aggregator/{{ user.img }} " height="100px" width="100px">
            </div>
            <div class="official">
            	<h3>Official Details </h3>
                <p>Website Linked : <a href="{{user.website_linked }}" target="_blank">{{ user.website_linked }}</a></p>
                <p>User Introduction : {{ user.user_introduction }}</p>
            </div>
			</div>
	</div>
		

        	   

	
		<footer>
			<div class="Manageby">
			<h4> MANAGE AND PUBLISHEDBY:</h4>
				<div>VAIBHAV BAJPAI ||  KUNAL RAJPUT  || KANIKA SINGHAL</div>
			</div>
			<div class="companylogo">
						<img id="img1" src="{% static '../static/image/book1.png' %}" alt="company logo" >
			</div>
			<div class="followus">
				<h4>FOLLOW US:</h4>
				<a href="https://www.facebook.com">
				<img id="link" alt="followus" src="{% static '../static/image/facebook.png' %}" >
				<a href="http://www.twitter.com">
				<img id="link" alt="followus" src="{% static '../static/image/twitter.png' %}">
				<a href="https://www.youtube.com">
				<img id="link" alt="followus" src="{% static '../static/image/youtube.png' %}" >
			</div>
		</footer>
 </body>
</html>

templates/register_company.html
  {% load static %}
<html>
<head>
			<link rel="stylesheet" type="text/css" href="{% static '../static/css/signupcompany.css' %}">
		
			


	
			<header>
			<div>
				<ul class="nav">

				   <li><a class="nav_left" href="{% url 'registration:home' %}">Home</a></li>
				   <li><a href="{% url 'registration:Search Job' %}">Search</a></li>
				  
				  
                    {% if flag == "on" %}
                        <li class="nav_right"><a href="">login</a>
                      <ul class="dropdown">
                      <li ><a href="{% url 'registration:login company' %}">Company</a></li>
                      <li ><a href="{% url 'registration:login User' %}"> User</a></li>

                      </ul>
                      <li class="nav_right"><a href="">Signup</a>
                      <ul class="dropdown">
                      <li><a href="{% url 'registration:registerCompany' %}">Company</a></li>
                      <li><a href="{% url 'registration:registerUser' %}">Job seeker</a></li>
                    {% endif %}
                    {% if flag == "off" %}
                      <li><a class="nav_left" href="{% url 'registration:Job Submit' %}">Post a job</a></li>
                        <li><a class="nav_left" href="{% url 'registration:profilecheck' %}">Profile</a></li>
                        <li><a class="nav_right" href="{% url 'registration:logout' %}">Logout</a></li>
                    {% endif %}
                  </ul>

				 
				</ul>
			</div>
			</header>
	</head>
	<body >
	<div class="image">
			<img id="img1" src={% static '../static/image/stickynote.png' %} alt="company logo" >
  
    </div>
                     
                     	
		            
			<div class="login">
				    
			        <form  method="post">
						<h1>Company</h1>
				     {% if messages %}
		                         <ul class="messages">
		                            {% for message in messages %}
		                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		                            {% endfor %}
		                         </ul>
		             {% endif %}

				     {% csrf_token %}
					 {{ form.as_p }}
			 
		  
		  <fieldset class="account-action">
			<input class="btn" type="submit" name="submit" value="Submit">
		   
		  </fieldset>
		</form>
		</div>

		
		
 </body>
</html>

templates/search.html
{% load static %}
<html>
	<head>
			<link rel="stylesheet" type="text/css" href="{% static './css/search.css' %}">
		
			


	
			<header>
			<div>
				<ul class="nav">
				  <li><a class="nav_left" href="{% url 'registration:home' %}">Home</a></li>
				   <li><a class="nav_left"href="{% url 'registration:Search Job' %}">Search</a></li>
				  
				  
                    {% if flag == "on" %}
                        <li class="nav_right"><a href="">login</a>
                      <ul class="dropdown">
                      <li ><a href="{% url 'registration:login company' %}">Company</a></li>
                      <li ><a href="{% url 'registration:login User' %}"> Job seeker</a></li>

                      </ul>
                      <li class="nav_right"><a href="">Signup</a>
                      <ul class="dropdown">
                      <li><a href="{% url 'registration:registerCompany' %}">Company</a></li>
                      <li><a href="{% url 'registration:registerUser' %}">Job seeker</a></li>
                    {% endif %}
                    {% if flag == "off" %}
                        <li><a class="nav_left" href="{% url 'registration:Job Submit' %}">Post a job</a></li>
						<li><a class="nav_left"href="{% url 'registration:profilecheck' %}">Profile</a></li>
                        <li><a class="nav_right"href="{% url 'registration:logout' %}">Logout</a></li>
                        
                    {% endif %}
                  </ul>
				</ul>
			</div>
			</header>
	</head>
	<body>
			<div style="">
				<div class="left_text">
				<div >
					{%  for JobDetails in list %}

					 <a href="{% url 'registration:application' JobDetails.details %}"> <p> Job Details :{{ JobDetails.details }}</p></a>
					 <p> Job Pay : {{ JobDetails.pay }}</p>
					 <p> Job Deadline : {{ JobDetails.deadline }}</p>
						<p> Genre : {{ JobDetails.genre }}</p>

					{% endfor %}
				</div>
				</div>
				<div  style="float:right; width:30%; padding:5%;">
				<div class="search">
					<h3> SEARCH:</h3>
					<form  method="post">
						{% csrf_token %}
						{{ form.as_p }}
						 <input type="submit" value="Submit" />
					 </form>

				</div>
				</div>
			</div>


		    <div></div>
            
	

	<!-- <footer>
			<div class="Manageby">
			<h4> MANAGE AND PUBLISHEDBY:</h4>
				<div>VAIBHAB BAJPAI ||  KUNAL RAJPUT  || KANIKA SINGHAL</div>
			</div>
			<div class="followus">
				<h4>FOLLOW US:</h4>
				<a href="https://www.facebook.com/">
				<img id="link" alt="followus" src="{% static './image/facebook.png' %}" >
				<a href="http://www.twitter.com">
				<img id="link" alt="followus" src="{% static './image/twitter.png' %}"> 
				<a href="https://www.youtube.com">
				<img id="link" alt="followus" src="{% static './image/youtube.png' %}" >
			</div>
		</footer> -->
	
		<script>
			var myIndex1=0;
			element1();
			function element1()
			{
				var i;
				var x=document.getElementsByClassName("mySlides");
				for(i=0;i<x.length;i++)
				{
				x[i].style.display="none";
				}
				myIndex1++;
				if(myIndex1 > x.length)
				{
				myIndex1=1;
				}
				x[myIndex1-1].style.display = "block";
				setTimeout(element1, 4000);
			}
			</script>
 </body>
</html>